### ISSUE TITLE
Update extension icon

### ISSUE THREAD

**Issue by amitness** [amitness/NC#10]
- [x] Find a relevant icon that allows reuse
- [x] Replace current icon with it
- [x] Add attributions to README

**Comment by amitness** [comment]
@prabinzz Looks like the icon is custom made?

**Comment by prabinzz** [comment]
Yeah, it is. I couldn't find related icons. 😄

**Comment by prabinzz** [comment]
@amitness  please change that.

**Comment by amitness** [comment]
Yup, tested it on Amazon. Great Job :+1:

**Comment by amitness** [comment]
How about a simple "Rs" as icon? Or the devanagiri one. Can you make a custom one like that?

**Comment by prabinzz** [comment]
@amitness How about real coin as an icon.. ?? It's just a thought. 😺 Any way. which is is Rs. / रु/ coin ???

**Comment by amitness** [comment]
@prabinzz Anything that looks good. Give it a try. It's all experimentation with design.

**Comment by prabinzz** [comment]
Ok, I'll give it a try.
