### ISSUE TITLE
Work on the Exchange Rate API

### ISSUE THREAD

**Issue by amitness** [amitness/NC#2]
https://www.nrb.org.np/exportForexXML.php?YY=2017&MM=07&DD=21&YY1=2017&MM1=07&DD1=22

**Comment by nepalbitcoin** [comment]
JSON >> 
https://www.nrb.org.np/exportForexJSON.php?YY=2017&MM=06&DD=21&YY1=2017&MM1=07&DD1=22

**Comment by amitness** [comment]
Even better :+1: . Thanks @nepalbitcoin

**Comment by prabinzz** [comment]
For latest data >> https://www.nrb.org.np/exportForexJSON.php

**Comment by amitness** [comment]
@prabinzz Great. Glad to see them giving APIs. Lots of possibilities if every gov service did that.
